syntax = "proto3";

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH
// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package yh;

import "google/protobuf/any.proto";

// 共用区

// 枚举

// 会话类型
// #region ChatType
enum ChatType {
  unknown1 = 0;
  user = 1;
  group = 2;
  bot = 3;
}
// #endregion ChatType

// 内容类型
// #region ContentType
enum ContentType {
  unknown2 = 0;
  text = 1;
  image = 2;
  markdown = 3;
  file = 4;
  form = 5; // 表单
  sticker = 7; // 表情
  html = 8;
  audio = 11; // 语音
  call = 13; // 语音电话
  a2ui = 14;
}
// #endregion ContentType

// 纯文本的内容类型
// #region ContentTypeTextOnly
enum ContentTypeTextOnly {
  TEXT_UNSPECIFIED = 0;
  TEXT_text = 1;
  TEXT_markdown = 2;
  TEXT_html = 3;
}
// #endregion ContentTypeTextOnly

// VIP 状态
// #region VipStatus
enum VipStatus {
  VIP_STATUS_NONE = 0; // 未开通
  VIP_STATUS_ACTIVE = 1; // 开通且未过期
  VIP_STATUS_EXPIRED = 2; // 开通且已过期
}
// #endregion VipStatus
// 枚举结束

// 响应状态
// #region Status
message Status {
  int64 request_id = 1;
  int32 code = 2;
  string msg = 3;
}
// #endregion Status

// 勋章信息
// #region MedalInfo
message MedalInfo {
  uint64 id = 1; // 勋章 ID
  string name = 2; // 勋章名称
  uint64 sort = 5; // 勋章顺序
}
// #endregion MedalInfo

// 备注信息
// #region RemarkInfo
message RemarkInfo {
  string remark_name = 1; // 备注名
  string phone = 2; // 手机号
  string extra_remark = 3; // 其他备注（格式为 JSON，示例：'[{"key":"他是","value":"我的朋友"},{"key":"职业","value":"打工人"}]'）
}
// #endregion RemarkInfo

// 个人信息
// #region ProfileInfo
message ProfileInfo {
  string last_active_time = 1; // 该用户上次活跃时间
  string introduction = 2; // 简介
  int32 gender = 3; // 性别: 1-男，2-女，3-其他
  uint64 birthday_timestamp = 4; // 生日时间戳
  string city = 5; // 城市
  string district = 6; // 地区
  string address = 7; // 详细地址
}
// #endregion ProfileInfo

// 通用状态响应
// #region StatusResponse
message StatusResponse {
  Status status = 1;
}
// #endregion StatusResponse

// 消息内容
// #region MsgContent
message MsgContent {
  string text = 1; // 信息文本
  string buttons = 2; // 按钮
  string image_url = 3; // 图片 URL
  string file_name = 4; // 欲发送文件名称
  string file_url = 5; // 欲发送文件 URL
  repeated string mentioned_id = 6; // @对象 ID ,可以填写多个
  string form = 7; // 表单消息
  string quote_msg_text = 8; // 引用信息文本
  string image = 9; // 欲发送图片 key/url(expression/abcdef.jpg)
  string post_id = 10; // 文章ID
  string post_title = 11; // 文章标题
  string post_content = 12; // 文章内容
  string post_content_type = 13; // 文章类型: 1-文本,2-Markdown
  string expression_id = 15; // 个人表情ID(不知道为啥为STR)
  string quote_image_url = 16; // 引用图片直链,https://...
  string quote_image_name = 17; // 引用图片文件名称
  int64 file_size = 18; // 欲发送文件大小
  string video_url = 19; // 欲发送视频 key/url(123.mp4),也是视频 URL
  int32 video_time = 20; // 视频时长
  string audio_url = 21; // 语音 key/url(123.m4a)
  int32 audio_time = 22; // 语音时长(单位秒)
  string quote_video_url = 23; // 引用视频直链,https://...
  int32 quote_video_time = 24; // 引用视频时长
  int64 sticker_item_id = 25; // 表情 ID
  int64 sticker_pack_id = 26; // 表情包 ID
  string room_name = 29; // 语音房间发送显示信息的文本
  string call_status_text = 32; // 语音通话状态文字
  int32 width = 33; // 图片的宽度
  int32 height = 34; // 图片的高度
  string tip = 37; // 提示信息
}
// #endregion MsgContent

// 标签
// #region Tag
message Tag {
  uint64 id = 1; // 标签 ID
  string group_id = 2; // 标签所属群聊 ID
  string text = 3;
  string color = 4;
}
// #endregion Tag

// 看板数据
// #region BotBoardMessage
message BotBoardMessage { // 如果要是 WS 的话对应 cmd 为 bot_board_message
  string bot_id = 1; // 机器人 ID
  string chat_id = 2; // 对象 ID
  ChatType chat_type = 3; // 对象类别
  string content = 4; // 看板内容
  ContentTypeTextOnly content_type = 5; // 看板内容类别
  int64 last_update_timestamp = 6; // 最后更新时间戳
  string bot_name = 7; // 设置看板机器人名称
}
// #endregion BotBoardMessage

// 机器人信息
// #region BotData
message BotData {
  /*
     12 疑似废弃,int 和 string 客户端均无报错
  */
  reserved 12;
  string bot_id = 1; // 机器人 ID
  string name = 2; // 机器人名称
  int64 name_id = 3; // 机器人名称 ID
  string avatar_url = 4; // 机器人头像 URL
  int64 avatar_id = 5; // 机器人头像 ID
  string introduction = 6; // 机器人介绍
  string create_by = 7; // 机器人创建者 ID
  int64 create_timestamp = 8; // 机器人创建时间戳
  int64 headcount = 9; // 使用人数
  bool private = 10; // 是否为私有: 0-公开，1-私有
  bool is_stop = 11; // 是否停用: 0-启用，1-停用
  bool always_agree = 13; // 自动进群: 0-不自动进群，1-自动进群
  bool prevent_deletion = 14; // 禁止删除
  bool do_not_disturb = 15; // 免打扰: 0-不免打扰，1-免打扰
  int64 ban_id = 16; // 封禁 ID
  int64 ban_until_timestamp = 17; // 封禁截至时间,时区 UTC+8
  bool top = 18; // 置顶: 0-未置顶，1-已置顶
  bool is_deleted = 19; // 是否删除,客户端会显示个已删除的标,虽然说实际上压根碰不到看到这个标的情况.
  bool group_limit = 20; // 限制进群: 0-允许进群，1-限制进群
  int32 field21 = 21; // 只知道是 int 类的,具体不知道
  string ban_reason = 22; // 封禁原因
}
// #endregion BotData

// 群聊数据
// #region GroupData
message GroupData {
  string group_id = 1;
  string name = 2;
  string avatar_url = 3;
  uint64 avatar_id = 4; // 头像 ID
  string introduction = 5;
  uint64 headcount = 6; // 群人数
  string create_by = 7; // 创建者
  bool direct_join = 8; // 进群免审核
  int32 permisson_level = 9; // 权限等级
  bool history_msg = 10; // 历史消息
  string category_name = 11; // 分类名
  uint64 category_id = 12; // 分类 ID
  bool private = 13; // 是否为私有群聊
  bool do_not_disturb = 14; // 免打扰
  uint64 community_id = 15; // 加入的社区 ID
  string community_name = 16; // 加入的社区名
  int64 ban_id = 17; // 封禁 ID
  int64 ban_until_timestamp = 18; // 群聊解禁时间戳,永久无此项,时区 Asia/Shanghai
  bool top = 19; // 会话置顶
  repeated string admin = 20; // 管理员列表
  int64 gag_until_timestamp = 21; // 禁言截止时间,时区 UTC+8,永久禁言为 -1
  string limited_msg_type = 22; // 被限制的消息类型,例如 1,2,3
  string owner = 23; // 群主
  bool recommandation = 24; // 是否加入群推荐
  bool is_gag = 25; // 是否被禁言
  repeated string tag_old = 26; // 标签(旧版)
  repeated Tag tag = 27;
  string my_group_nickname = 28; // 我的群昵称
  string group_code = 29; // 群口令
  bool hide_group_members = 30; // 隐藏群成员（开启时为 1）
  int64 field31 = 31; // 未知
  bool auto_delete_message = 32; // 消息自动销毁时间
  bool deny_members_upload_to_group_disk = 33; // 禁止群成员上传文件到群云盘（开启时为 1）
  string ban_reason = 34; // 封禁原因
}
// #endregion GroupData

// Sender 发送者信息
// #region Sender
message Sender {
  string chat_id = 1; // 发送者 ID
  ChatType chat_type = 2; // 发送者类型
  string name = 3; // 发送者名称
  string avatar_url = 4; // 头像 URL
  bool is_vip = 5; // 是否为 VIP
  repeated string tag_old = 6; // 标签(旧版显示)
  repeated Tag tag = 7; // 标签
}
// #endregion Sender

// 命令内容
// #region Cmd
message Cmd {
  uint64 cmd_id = 1; // 指令 ID
  string name = 2; // 指令名
  int32 type = 4; // 指令类型（1-普通指令, 2-直发指令, 5-自定义输入指令）
}
// #endregion Cmd

// 这里不会有 WS 的共用内容

// 共用区结束

// User 相关

// 获取用户自身信息
// #region UserInfo
message UserInfo {
  Status status = 1;
  message Data {
    string id = 1; // 用户 ID
    string name = 2; // 用户名
    int32 field3 = 3; // 不知道干啥的,反正 proto 里面没废弃
    string avatar_url = 4; // 头像 URL
    int64 avatar_id = 5; // 头像 ID
    string phone = 6; // 手机号
    string email = 7; // 邮箱
    double coin = 8; // 金币数
    bool is_vip = 9; // 是否为 VIP
    int64 vip_expired_timestamp = 10; // VIP 过期时间
    VipStatus vip_status = 11; // VIP 开通状态
    string invitation_code = 12; // 邀请码
  }

  Data data = 2;
}
// #endregion UserInfo

// 获取用户信息
// #region GetUserRequest
message GetUserRequest {
  string id = 2;
}
// #endregion GetUserRequest

// #region GetUserResponse
message GetUserResponse {
  /*
     4402 该用户不存在
     7100 因违反相关规定，该用户被封禁
  */
  Status status = 1;
  Data data = 2; // 数据
  message Data {
    string id = 1; // 用户 id
    string name = 2; // 用户名
    uint64 name_id = 3; // 名称 ID
    string avatar_url = 4; //头像 URL
    uint64 avatar_id = 5; // 头像 ID
    repeated MedalInfo medal = 6; // 勋章信息
    string register_time = 7; // 注册时间,格式: YYYY-MM-DD hh:mm:ss
    bool do_not_disturb = 8; // 免打扰 ~~别问咋抓出来的.勇敢去猜!~~
    int64 ban_id = 9; // 封禁 ID
    int64 ban_until_timestamp = 10; // 封禁结束时间(时间戳),永久无此项
    int32 online_day = 11; // 在线天数
    int32 continuous_online_day = 12; // 连续在线天数
    bool is_vip = 13; // 是否为 vip
    uint64 vip_expired_timestamp = 14; // VIP 过期时间(时间戳)
    VipStatus vip_status = 15; // VIP 情况
    bool is_blocked = 16; // 黑名单
    bool top = 17; // 置顶会话
    RemarkInfo remark_info = 18; // 备注信息
    ProfileInfo profile_info = 19; // 用户资料信息
    string ip_geo = 20; // IP归属地（国家）
    string ban_reason = 21; // 封禁原因
  }
}
// #endregion GetUserResponse

// 获取自身勋章
// #region GetSelfMedal
message GetSelfMedal {
  Status status = 1;
  repeated MedalInfo medal = 2; // 勋章信息
}
// #endregion GetSelfMedal

// 编辑自身昵称
// #region EditNicknameRequest
message EditNicknameRequest {
  string name = 3; // 修改后的名称
}
// #endregion EditNicknameRequest

// 更改自身头像
// #region EditAvatarRequest
message EditAvatarRequest {
  string url = 2; // 完整 URL(https://...)
}
// #endregion EditAvatarRequest

// Msg 相关

// 发送消息
// #region SendMsgRequest
message SendMsgRequest {
  string msg_id = 2; // 信息 ID
  string chat_id = 3; // 欲发送到的信息对象
  ChatType chat_type = 4; // 欲发送到的信息对象的类别
  MsgContent content = 5; // 消息内容
  ContentType content_type = 6; // 消息类别
  int64 command_id = 7; // 所使用命令 ID
  string quote_msg_id = 8; // 引用信息 ID
  // Media media = 9; // 其实没啥用,不要看这个!!!!!
  // message Media { // 在 media 发送对象为，图片/音频/视频
  //   string file_key = 1; // 发送对象 key (就是上传后七牛对象存储给你返回的 file_key)
  //   string file_hash = 2; // 发送对象上传返回哈希
  //   string file_type = 3; // 发送对象类别，image/jpeg-图片，video/mp4-音频
  //   int64 image_height = 5; // 图片高度
  //   int64 image_width = 6; // 图片宽度
  //   int64 file_size = 7; // 发送对象大小
  //   string file_key2 = 8; // 发送对象key,和1一样,据说不写会报错
  //   string file_suffix = 9; // 发送对象后缀名
  // }
}
// #endregion SendMsgRequest

// 编辑消息的 Proto 可以和 SendMsg 共用,这里不写了

// 通过消息序列列出消息
// #region ListMsgBySeqRequest
message ListMsgBySeqRequest {
  uint64 msg_start = 3; // 从第 N 个消息开始
  ChatType chat_type = 4; // 对象类型
  string chat_id = 5; // 对象 ID
}
// #endregion ListMsgBySeqRequest

// #region ListMsgResponse
message ListMsgResponse {
  Status status = 1;
  repeated MsgData data = 2; // 消息数据
  int32 total = 3; // 消息数

  message MsgData {
    string msg_id = 1; // 消息 ID
    Sender sender = 2;
    string direction = 3; // 消息位置: 左边 left/右边 right
    ContentType content_type = 4;
    MsgContent content = 5;
    uint64 send_timestamp_ms = 6; // 时间戳(毫秒)
    Cmd cmd = 7; // 指令
    uint64 recall_timestamp = 8; // 消息撤回时间
    string quote_msg_id = 9; // 引用消息 ID
    uint64 msg_seq = 10;
    uint64 edit_timestamp = 12; // 最后编辑时间
  }
}
// #endregion ListMsgResponse

// 通过列出消息
// #region ListMsgRequest
message ListMsgRequest {
  int32 msg_count = 2; // 获取消息数
  string msg_id = 3; // 从指定消息 ID 开始
  ChatType chat_type = 4; // 对象类型
  string chat_id = 5; // 对象 ID
}
// #endregion ListMsgRequest

// 列出包含请求 msg_id 消息
// #region ListMsgByMidSeqRequest
message ListMsgByMidSeqRequest {
  uint64 msg_seq = 3; // 开始消息的 seq
  ChatType chat_type = 4;
  string chat_id = 5;
  uint64 unknown = 6; // 不知道干啥的
  int32 msg_count = 7; // 获取的消息数
  string msg_id = 8;
}
// #endregion ListMsgByMidSeqRequest

// 按钮事件回调消息
// #region ButtonReportRequest
message ButtonReportRequest {
  string msg_id = 2; // 消息 ID
  ChatType chat_type = 3; // 对象类型
  string chat_id = 4; // 对象 ID
  string user_id = 5; // 按钮事件发送者 ID
  string button_value = 6; // 欲点击按钮的值
}
// #endregion ButtonReportRequest

// 撤回消息
// #region RecallMsg
message RecallMsg {
  repeated string msg_id = 2; // 要撤回的信息 ID
  string chat_id = 3; // 信息所属对象 ID
  ChatType chat_type = 4; // 信息所属对象类型
}
// #endregion RecallMsg

// 获取消息列表内的图片
// #region PicListMsgByMidSeqRequest
message PicListMsgByMidSeqRequest {
  uint64 image_id = 3; // 图片 ID
  ChatType chat_type = 4; // 会话类型
  string chat_id = 5; // 会话 ID
  uint64 earlier_quantities = 6; // 前面（消息时间较早）的图片数量
  uint64 latest_quantities = 7; // 后面（消息时间较新）的图片数量
}
// #endregion PicListMsgByMidSeqRequest

// Bot

// #region BotInfoRequest
message BotInfoRequest {
  string id = 2; // 机器人 ID
}
// #endregion BotInfoRequest

// 获取机器人信息返回信息
// #region BotInfoResponse
message BotInfoResponse {
  Status status = 1;
  BotData data = 2;
}
// #endregion BotInfoResponse

// 看板
// #region BoardRequest
message BoardRequest {
  string id = 3; // 对象 ID
  ChatType chat_type = 4; // 对象类型
}
// #endregion BoardRequest

// 获取看板返回
// #region BoardResponse
message BoardResponse {
  Status status = 1;
  BotBoardMessage data = 2;
}
// #endregion BoardResponse

// 创建机器人
// #region CreateBotRequest
message CreateBotRequest {
  string name = 2; // 机器人名称
  string introduction = 3; // 机器人简介
  string avatar_url = 4; // 头像 URL
  bool private = 5; // 是否私有(0-公开，1-私有)
}
// #endregion CreateBotRequest

// #region CreateBotResponse
message CreateBotResponse {
  Status status = 1;
  BotData data = 2;
}
// #endregion CreateBotResponse

// 获取使用者列表
// #region ListFollowerRequest
message ListFollowerRequest {
  Data data = 2;
  string bot_id = 3; // 机器人 ID
  string keywords = 4; // 搜索关键词

  message Data {
    int32 size = 1; // 分页大小
    int32 page = 2; // 页数
  }
}
// #endregion ListFollowerRequest

// #region ListFollowerResponse
message ListFollowerResponse {
  Status status = 1;
  repeated User user = 2;
  int32 totol = 3; // 总数

  message User {
    string user_id = 1; // 用户 ID
    string name = 2; // 昵称
    string avatar_url = 4; // 头像 URL
    bool is_vip = 6; // 是否 VIP
  }
}
// #endregion ListFollowerResponse

// 获取加入的群列表
// #region JoinGroupListRequest
message JoinGroupListRequest {
  Data data = 2;
  string bot_id = 3; // 机器人 ID
  string keywords = 4; // 搜索关键词

  message Data {
    int32 size = 1; // 分页大小
    int32 page = 2; // 页数
  }
}
// #endregion JoinGroupListRequest

// #region JoinGroupListResponse
message JoinGroupListResponse {
  Status status = 1;
  repeated Group group = 2;
  int32 total = 3; // 总数

  message Group {
    string id = 1; // 群聊 ID
    string name = 2; // 群聊名称
    string avatar_url = 3; // 头像 URL
  }
}
// #endregion JoinGroupListResponse

// Conversation

// 获取对话列表
// #region ConversationListRequest
message ConversationListRequest {
  string md5 = 2; // 上次获取对话的 MD5, 如果与服务端一致则返回空列表
}
// #endregion ConversationListRequest

// 列出对话
// #region ConversationListResponse
message ConversationListResponse {
  Status status = 1;
  repeated Data data = 2;
  int32 total = 3; // 列表中对话的数量
  string md5 = 4; // 对话列表的 md5

  message Data {
    string chat_id = 1; // 对象 ID
    ChatType chat_type = 2; // 对象类型
    string remark = 3; // 备注名称
    string chat_content = 4; // 消息内容
    uint64 timestamp_ms = 5; // 加入对话列表时间戳(毫秒)
    int32 unread_msg = 6; // 未读消息数
    bool at = 7; // 是否被@
    uint64 avatar_id = 8; // 头像 ID
    string avatar_url = 9; // 头像 URL
    bool do_not_disturb = 11; // 免打扰
    uint64 send_timestamp = 12; // 消息发送时间戳(秒)
    bool is_vip = 13; // 是否为 VIP
    AtData at_data = 14; // @数据
    string name = 15; // 用户真实名称
    int32 certification_level = 16; // 认证,1-官方, 2-地区

    message AtData {
      uint64 unknown = 1; // 似乎是名称 ID
      string mentioned_id = 2; // 被@的 ID,感觉没啥用
      string mentioned_name = 3; // 被@的名称,感觉也没啥用
      string mentioned_in = 4; // @消息所属的对话 ID(例如群 ID),感觉还没啥用
      string mentioner_id = 6; // 发起@的对象 ID
      string mentioner_name = 7; // 发起@对象的名称
      uint64 msg_seq = 8; // 发起@的消息序列
    }
  }
}
// #endregion ConversationListResponse

// Friend
// #region AddressBookListRequest 
message AddressBookListRequest {
  string md5 = 2; // 上一次通讯录的 MD5,如果和服务端一致则返回空列表
}
// #endregion AddressBookListRequest

// 聊天对话列表
// #region AddressBookListResponse
message AddressBookListResponse {
  Status status = 1;
  repeated Data data = 2;
  string md5 = 3;

  // 列表数据
  message Data {
    string list_name = 1; // 聊天对象列表名称，为"用户"，"我加入的群聊"，"机器人"
    repeated DataList data = 2;
    ChatType chat_type = 3;

    // 聊天对象数据
    message DataList {
      string chat_id = 1; // 聊天对象 ID
      string remark = 2; // 聊天对象备注名称
      string avatar_url = 3; // 聊天对象头像 url
      int32 permisson_level = 4; // 群权限等级(普通用户无此项(数值为 0 或无此项),群主 100,管理员 2),只有群列表才有此项
      bool no_disturb = 5; // 免打扰
      //int32 field6 = 6; // 未知
      string name = 8; // 聊天对象真实名称
    }
  }
}
// #endregion AddressBookListResponse

// 申请/邀请列表
// #region RequestListResponse
message RequestListResponse {
  Status status = 1;
  message Request {
    string receiver_name = 1; // 接收者名称
    string receiver_avatar = 2; // 接收者头像
    string name = 3; // 请求方名称
    string avatar = 4; // 请求方头像
    string group_name = 5; // 群组名称
    string group_avatar = 6; // 群组头像
    string inviter_id = 7; // 邀请者 ID (字段8同此含义)
    int32 source_type = 9; // 来源类型
    int32 target_type = 10; // 目标类型
    string target_id = 11; // 目标 ID
    string receiver_id = 12; // 接收者 ID
    int32 result = 13; // 处理结果
    int64 processed_at = 14; // 处理时间戳
    int64 invite_at = 16; // 邀请时间戳
    string invite_at_str = 17; // 邀请时间字符串
    int32 request_id = 18; // 请求 ID
    string bot_name = 19; // 机器人名称
    string bot_avatar = 20; // 机器人头像
    string processor_name = 22; // 处理者名称
    string note = 23; // 备注信息
    bool is_vip = 24; // 是否为 VIP
  }
  repeated Request requests = 2; // 请求列表
  int32 total = 3; // 总请求数
  int32 pending = 4; // 待处理请求数
}
// #endregion RequestListResponse

// group-tag
// #region TagMemberRequest 
message TagMemberRequest {
  Data data = 2;
  message Data {
    int32 size = 1; // 分页大小
    int32 page = 2; // 页数
  }
  string group_id = 3; // 标签所处群聊 ID
  int64 tag_id = 4; // 标签 ID
}
// #endregion TagMemberRequest

// group

// 获取群聊信息
// #region GroupInfoRequest 
message GroupInfoRequest {
  string group_id = 2; // 群聊 ID
}
// #endregion GroupInfoRequest

// #region GroupInfoResponse
message GroupInfoResponse {
  Status status = 1;
  GroupData data = 2;
  repeated BotData bot = 3;
}
// #endregion GroupInfoResponse

// 获取群成员
// #region ListMemberRequest
message ListMemberRequest {
  Data data = 2;

  message Data {
    int32 size = 1; // 分页大小
    int32 page = 2; // 页数
  }

  string group_id = 3; // 群聊 ID
  string keywords = 4; // 搜索关键词
}
// #endregion ListMemberRequest

// #region ListMemberResponse
message ListMemberResponse {
  Status status = 1;
  repeated User user = 2;
  message User {
    string group_id = 1;
    UserInfo user_info = 2;

    message UserInfo {
      string user_id = 1;
      string name = 2;
      string avatar_url = 4;
      bool is_vip = 6;
    }
    int32 permission_level = 3; // 权限等级, 群主 100 管理员 2 普通用户无/0
    int64 gag_timestamp = 4; // 禁言时间戳
    bool is_gag = 5; // 是否被禁言
  }
  int32 total = 3; // 总数
}
// #endregion ListMemberResponse

// 编辑群信息
// #region EditGroupRequest
message EditGroupRequest {
  string group_id = 2; // 目标群聊 ID
  string name = 3; // 群聊名称
  string introduction = 4; // 群聊简介
  string avatar_url = 5; // 群聊头像 url
  bool direct_join = 6; // 进群免审核,1 为开启
  bool history_msg = 7; // 历史消息,1 为开启
  string category_name = 8; // 分类名
  uint64 category_id = 9; // 分类 ID
  bool private = 10; // 是否私有,1 为私有
  bool hide_group_members = 11; // 隐藏群成员
}
// #endregion EditGroupRequest

// 获取群机器人列表
// #region BotListRequest
message BotListRequest {
  string group_id = 2; // 群聊 ID
}
// #endregion BotListRequest

// 获取群机器人列表
// #region BotListResponse
message BotListResponse {
  Status status = 1;
  repeated BotData bot = 2;

  repeated InstructionData instruction = 3;

  message InstructionData {
    int64 id = 1;
    string bot_id = 2;
    string name = 3; // 指令名
    string desc = 4; // 指令描述
    int32 type = 5; // 指令类型（1-普通指令, 2-直发指令, 5-自定义输入指令）
    string hint_text = 6; // 输入框提示文字
    string default_text = 7; // 输入框默认文字
    // int32 hidden/del_flag = 8; // 是否隐藏/删除,猜的,有误欢迎指正
    int64 sort = 9; // 和排序相关 不确定
    string form = 10; // 表单
    string bot_name = 11; // 机器人名称
  }
  repeated MenuData menu = 4; // 快捷菜单相关

  message MenuData {
    int64 id = 1;
    string bot_id = 2;
    // int32 hidden/del_flag = 3; // 是否隐藏/删除,猜的
    string name = 4;
    string content = 5; // 内容
    int32 menu_type = 6; // 按钮类型: 1-普通按钮 2-选中按钮 3-下拉选择
    int64 create_timestamp = 7;
    // 8,9没找到
    int32 menu_action = 10; // 操作类型
    string select = 99; // 选择的选项,在选择按钮的时候也作为状态,选中为 1,未选中为 0
  }
}
// #endregion BotListResponse

// 获取群口令关联群聊
// #region InfoAddFriendRequest
message InfoAddFriendRequest {
  string keyword = 2; // 欲要搜索的群口令
}
// #endregion InfoAddFriendRequest

// #region InfoAddFriendResponse
message InfoAddFriendResponse {
  Status status = 1;
  GroupData data = 2;
}
// #endregion InfoAddFriendResponse

// 创建群聊
// #region CreateGroupRequest
message CreateGroupRequest {
  string name = 2; // 群聊名称
  string introduction = 3; // 群简介
  string avatar_url = 4; // 头像 URL
}
// #endregion CreateGroupRequest

// #region CreateGroupResponse
message CreateGroupResponse {
  Status status = 1;
  string group_id = 2; // 新群聊 ID
}
// #endregion CreateGroupResponse

// 解散群聊
// #region DismissGroupRequest
message DismissGroupRequest {
  string group_id = 2;
}
// #endregion DismissGroupRequest

// instruction
// 获取私聊指令
// #region GetBotInstructionRequest
message GetBotInstructionRequest {
  string bot_id = 3;
}
// #endregion GetBotInstructionRequest

// #region GetBotInstructionResponse
message GetBotInstructionResponse {
  Status status = 1;
  Data data = 2;
  message Data {
    uint64 command_id = 1; // 指令 id
    string bot_id = 2; // 机器人 id
    string command_name = 3; // 指令名称
    int32 instruction_type = 5; // 指令类型: 1-普通指令，2-直发指令，5-自定义输入指令
    string command_default_text = 7; // 指令输入框默认文本
    string command_settings_json = 10; // 指令设置 JSON（表单指令，自定义输入指令）
  }
}
// #endregion GetBotInstructionResponse

// chat-ws-go

// chat-ws-go 共用区

// WsInfo
// #region WsInfo
message WsInfo {
  string seq = 1; // 请求标识码,可以不管
  string cmd = 2; // 操作类型
}
// #endregion WsInfo

// WsWrapper
// 这里是 Ws 消息的外层
// #region WsWrapper
message WsWrapper {
  WsInfo info = 1;
  google.protobuf.Any data = 2; // Any
}
// #endregion WsWrapper

// chat-ws-go 共用区结束

// 心跳包响应
// #region HeartbeatAckResponse
message HeartbeatAckResponse {
  WsInfo info = 1; // 响应数据,info.cmd = heartbeat_ack
}
// #endregion HeartbeatAckResponse

// MsgInput 实际上是草稿同步
// #region MsgInput
message MsgInput { // 对应的 cmd: draft_input
  string chat_id = 1; // 对象ID
  string input = 2; // 草稿内容,注意是覆盖不是合并也不是追加
}
// #endregion MsgInput

// PushMessage
// #region PushMessage
/*
   对应 cmd:
   push_message
   edit_message
   blocked_message
*/
message PushMessage {
  // blocked_message 只有 1,3,4 字段
  string msg_id = 1;
  Sender sender = 2; // 发送者信息,编辑消息无此项
  string recv_id = 3; // 接收者 ID,不知道为啥到编辑这里就和 4 一样了
  string chat_id = 4; // 会话 ID
  ChatType chat_type = 5; // 会话类型,编辑消息无此项
  MsgContent content = 6; // 消息内容,注意编辑消息的会话内容和发送消息可以共用但是编辑消息有缺失
  ContentType content_type = 7;
  uint64 timestamp = 8; // 时间戳(毫秒),编辑消息无此项
  Cmd cmd = 9; // 指令,编辑消息无此项(客户端限制不让编辑指令消息)
  uint64 delete_timestamp = 10; // 撤回消息时间,和8差别不大,编辑消息无此项
  string quote_msg_id = 11; // 引用消息ID
  uint64 msg_seq = 12; // 消息序列,在撤回时也是被撤回消息的序列,注意撤回消息存在部分字段缺失
  uint64 edit_timestamp = 14; // 编辑时间,只有编辑消息有此项
}
// #endregion PushMessage

// 有人邀请我
// #region InviteApplyResponse
message InviteApplyResponse {
  WsInfo info = 1; // info.cmd = invite_apply
}
// #endregion InviteApplyResponse

// 流式消息
// #region StreamMessage
message StreamMessage { // 对应 cmd: stream_message
  string msg_id = 1; // 消息 ID
  string recv_id = 2; // 接收者 ID,群聊的时为群聊的 ID,私聊是自己的 ID
  string chat_id = 3; // 会话 ID
  string content = 4; // 需要追加的消息内容
}
// #endregion StreamMessage

// 语音消息
// #region LiveMessage
message LiveMessage { // 对应 cmd: live_video_user_hang_up
  string msg_id = 1; // 语音消息 ID
  string cmd = 5; // 指令,例如 live_video_user_hang_up
}
// #endregion LiveMessage

// 机器人看板更新推送
// 和 BotBoardMessage 相同
